spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  mvc:
    favicon:
      enabled: false
security:
  jwt:
    token:
      header-name: Authorization
      header-prefix: Bearer
      secret-key: SECRET_KEY
      expire-time: 3600000